### ISSUE TITLE
Duplicate values in "openehr_external_terminologies.xml"

### ISSUE THREAD

**Issue by neoehr** [openEHR/terminology#11]
1. Codeset "IANA_media-types" has a duplicate values in lines 452 and 463:

"application/vnd.openxmlformats-officedocument.wordprocessingml.document"

2. Codeset "languages" has duplicate values:

- "English (Caribbean)" on line 307 should have a distinct value (now it has the same as "English" on line 298):

```
<code value="en" description="English"/>
<code value="en" description="English (Caribbean)"/>
```

- Similar for "ko":

```
<code value="ko" description="Korean"/>
<code value="ko" description="Korean (Johab)"/>
```

- Similar for "sr":

```
<code value="sr" description="Serbian (Cyrillic)"/>
<code value="sr" description="Serbian (Latin)"/>
```

- Similar for "es":

```
<code value="es" description="Spanish (Spain ? Traditional)"/>
<code value="es" description="Spanish (Spain ? Modern)"/>
```

https://github.com/openEHR/terminology/blob/master/openEHR_RM/openehr_external_terminologies.xml

**Comment by sebastian-iancu** [comment]
reported as https://openehr.atlassian.net/browse/SPECPR-403
