### ISSUE TITLE
Is the rubric "Electrical potential time" correct?

### ISSUE THREAD

**Issue by ppazos** [openEHR/terminology#12]
From the terminology file: `<concept id="655" rubric="Electrical potential time"/>`

I believe the property should be "Electrical potential" which is measured in volts, but not sure why the "time" is there. Maybe a typo?

**Comment by wolandscat** [comment]
I'm an elec eng and I don't even know what 'electrical potential time' is! The only thing I can think of is charge time i.e. for capacitive tissue, capacitive devices. But I don't see the term online. And it's not in [UCUM](https://ucum.org/ucum.html).

Plus, capacitance is 501, and 'Voltage, electrical' is 374.

I don't know where these terms came from originally, but I think they were copied in from some old software, so this could be a very old typo. Heath Frankel might know. Working hypothesis - it's a typo to be fixed.

**Comment by ppazos** [comment]
Thanks @wolandscat if that's a typo, there translations might be working as well. One not is after I reported this I found the voltage entry too. Though voltage measures a difference in electrical potential.

I'm not an electrical engineer though! :)

BTW I tried to get these properties from UCUM but I didn't find them there. I know this is being used in the archetype editor to constraint dv_quantity possible units.

**Comment by ppazos** [comment]
Checking the UCUM file https://ucum.org/ucum-essence.xml

There is an "electric potential level", there is no "electric potential time".

Also, we have "electrical" instead of "electric", and UCUM only has "electric" not "electrical".

https://github.com/openEHR/terminology/blob/master/openEHR_RM/en/openehr_terminology.xml#L104-L109

IMO we should follow UCUM. There might be other values to fix, these are the only ones that caught my attention.

**Comment by wolandscat** [comment]
Agree in general on using UCUM terms - only thing to be careful of is consistency across large numbers of terms e.g. 'electrical xyz' -> 'electric xyz' and so on.

**Comment by ppazos** [comment]
Thanks @wolandscat when searching online I can't find "electrical xxx" I found "electric xxx". Like searching "electrical charge" I can only see "electric charge" results.

**Comment by sebastian-iancu** [comment]
reported now as https://openehr.atlassian.net/browse/SPECPR-404
