### ISSUE TITLE
openEHR external terminologies file probably not accurate name

### ISSUE THREAD

**Issue by atalagk** [openEHR/terminology#2]
Hi, this is simply a list of international country codes.
I think we need a living document where we document external terminology systems, similar to [HL7 OID registry](https://www.hl7.org/oid/index.cfm).
Examples:

`<TerminologyIdentifiers` VSAB="SNOMED-CT" SourceName="SNOMED Clinical Terms" Authority="SNOMED International" Hl7Oid="2.16.840.1.113883.6.96" />`
`<TerminologyIdentifiers VSAB="LOINC" SourceName="Logical Observation Identifier Names and Codes" Authority="Regenstrief Institute" Hl7Oid="2.16.840.1.113883.6.1" />`
`<TerminologyIdentifiers VSAB="ICD10" SourceName="International Classification of Diseases, 10th Revision" Authority="WHO" Hl7Oid="2.16.840.1.113883.6.3" />`

This is actually captured in terminology.xml files in both Ocean Archetype Editor and Template Designer.
See attached HL7 external terminology systems OID file
[HL7_ExternalTerminologyOID_Report(Mar2017).xlsx](https://github.com/openEHR/terminology/files/840117/HL7_ExternalTerminologyOID_Report.Mar2017.xlsx)

**Comment by sebastian-iancu** [comment]
reported as https://openehr.atlassian.net/browse/SPECPR-405
