### ISSUE TITLE
Add modern codes for media types in external terminology

### ISSUE THREAD

**Issue by ppazos** [openEHR/terminology#6]
This https://github.com/openEHR/terminology/blob/master/openEHR_RM/openehr_external_terminologies.xml#L399-L464

On

`<codeset issuer="IANA" openehr_id="media types" external_id="IANA_media-types">`

Doesn't include types used today like:

```
                        "image/jp2",
                        "video/H264",
                        "video/mp4",
                        "video/ogg",
                        "video/mpeg",
                        "audio/mp4",
                        "audio/ogg",
                        "audio/vorbis",
                        "audio/mpeg3"
```

**Comment by sebastian-iancu** [comment]
reported as https://openehr.atlassian.net/browse/SPECPR-402
