### ISSUE TITLE
Composition category "episodic" was included but is not yet specified

### ISSUE THREAD

**Issue by ppazos** [openEHR/terminology#7]
The "episodic" and anything in between event and persistent is currently under discussion. Not sure why the episodic category was included in the terminology files.

**Comment by freshehr** [comment]
I was pretty certain that it was agreed - not sure we agreed (or can agree!) an exact definition but it was agreed to add it as far as I am aware - I'll check

**Comment by ppazos** [comment]
I think there is an open discussion in Discourse, since we need to define the scope and behavior for each new category. Also the current code assigned is the same as other code

`<Concept Language="en" ConceptID="435" Rubric="laboratory"/>`

**Comment by freshehr** [comment]
@ppazos  - where are you picking is up from

```<Concept Language="en" ConceptID="435" Rubric="laboratory"/>```

It is not in the openEHR terminology file. Is this in the older AE-supplied file?

I'd like ot close this issue as the consensus in SEC seems to be to stick with 'episodic'

**Comment by freshehr** [comment]
Discussed in Discourse /JIRA - agreed to stay with 'episodic'
