### ISSUE TITLE
What about the use of RDF format

### ISSUE THREAD

**Issue by ghost** [openEHR/terminology#8]
Hi, 

I would like to propose the use of RDF format instead of pure xml. What do you guys think?

Best Regards,
Silvio

**Comment by freshehr** [comment]
I'm not sure I see a particular advantage, Silvio. If anything I would be more interested in using the FHIR Valueset or Codesystem formats. Can you explain the advantage of RDF here?

**Comment by serefarikan** [comment]
I'd like to second Ian's question, also , even tough there is nothing wrong with having this discussion here, discourse would be a better medium for it. happy to be corrected.

**Comment by ghost** [comment]
Hi guys,
So for the question:
> I'm not sure I see a particular advantage, Silvio. If anything I would be more interested in using the FHIR Valueset or Codesystem formats. Can you explain the advantage of RDF here?

It would be a good enchantment for interoperability and other things explained here: https://www.hl7.org/fhir/rdf.html

**Comment by freshehr** [comment]
Hi @silviodc - that is a much broader conversation than just the openEHR terminology definitions. I agree with Seref - why not raise it on discourse.openehr.org. There has historically been a lot of work looking at using RDF to describe openEHR concepts, and it drifts in and out of the FHIR conversations, but I'm not convinced that it has enough real-world traction (in healthIT) to put a lot of effort into it - but let's have that discussion. As I said abpve if I was to re-formulate the xml into anything it would be FHIR codesystems or valuesets and sticking to JSON as the preferred format.

**Comment by serefarikan** [comment]
Agreed with @freshehr  again. Just a minor note, SMART on FHIR originally started based on RDF, then ended up what it is now. So you may also want to visit the SMART community and ask about their experience with RDF @silviodc 
I think we should close this issue now, because it is not really an issue, more of a wider discussion. I'm sure it would make an interesting heading in discourse ;)
